config/routes.rb
Rails.application.routes.draw do
  resources :stores do
    resources :menus
    resources :beacons
    resources :loyalty_programs
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users

  get 'api/v1/beacon/get' => 'api/v1/beacon#get'
  post 'api/v1/payment/pay' => 'api/v1/payment#pay'
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  belongs_to :store
  has_many :items, :dependent => :destroy
  validates_presence_of :name
  validates_presence_of :description
  accepts_nested_attributes_for :items, :allow_destroy => true
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_store
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def show
    respond_with(@menu)
  end

  def new
    @menu = @store.menus.new
    @menu.items.build
    respond_with(@menu)
  end

  def edit
  end

  def create
    @menu = @store.menus.new(menu_params)
    if @menu.save
      flash[:notice] = 'Menu was successfully created.'
    end

    respond_with(@store)
  end

  def update
    if @menu.update_attributes!(menu_params)
      flash[:notice] = 'Menu was successfully updated.'
    end
    respond_with(@store)
  end

  def destroy
    @menu.destroy
    respond_with(@store)
  end

  private
  def set_store
    @store = Store.find(params[:store_id])
  end

  def set_menu
    @menu = Menu.find(params[:id])
  end

  def menu_params
    params.require(:menu).permit(:name, :description, :items_attributes => [:name, :description, :price, :id, :_destroy])
  end
end

app/views/menus/_form.html.erb
<%= simple_form_for @menu, :url => @menu.new_record? ? store_menus_path : store_menu_path(@store, @menu),
                    :method => @menu.new_record? ? :post : :patch, :html => {:data => {:validate => 'parsley'}} do |f| %>
<%= f.error_notification %>

<div class="form-inputs">
  <%= f.input :name %>
  <%= f.input :description %>

  <h3>Items</h3>
  <%= link_to_add_association f, :items, :"data-association-insertion-node" => ".itemsTable tbody",:"data-association-insertion-method" => "append" do %>
    <btn class="btn btn-default">Add New Item</btn>
  <% end %>
  <table class="itemsTable table">
    <thead>
    <th width="300">Name</th>
    <th width="300">Price</th>
    <th width="500">Description</th>
    <th></th>
    </thead>
    <tbody>
    <%= f.simple_fields_for :items do |i|%>
      <%= render 'item_fields', :f => i%>
    <% end %>
    </tbody>
  </table>
</div>

<div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to 'Back', store_path(@store), :class => 'btn btn-danger' %>
</div>
<% end %>

app/views/menus/_item_fields.html.erb
<tr class="nested-fields">
  <td>
    <%= f.input :id, :as => :hidden %>
    <%= f.input_field :name, placeholder: 'Item Name', class: ' form-control' %>
  </td>
  <td><%= f.input_field :price, placeholder: 'Price', class: ' form-control' %></td>
  <td><%= f.input_field :description, placeholder: 'Some description for this time...', class: ' form-control' %></td>

  <td>
    <%= link_to_remove_association f do%>
      <i class="remove-nested-td glyphicon glyphicon-remove"></i>
    <% end %>
  </td>
</tr>

app/views/menus/edit.html.erb
<div class="container">
  <h1>Edit menu for <%= @store.name %></h1>

  <%= render 'form' %>

</div>

app/views/menus/new.html.erb
<div class="container">
  <h1>New menu for <%= @store.name %></h1>

  <%= render 'form' %>

</div>