config/routes.rb
Rails.application.routes.draw do
  resources :stores do
    resources :menus
    resources :beacons
    resources :loyalty_programs
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users

  get 'api/v1/beacon/get' => 'api/v1/beacon#get'
  post 'api/v1/payment/pay' => 'api/v1/payment#pay'
end

app/models/beacon.rb
class Beacon < ActiveRecord::Base
  belongs_to :store
  has_one :menu
  validates_presence_of :b_id
  validates_uniqueness_of :b_id
  validates_presence_of :menu_id
end

app/controllers/api/v1/beacon_controller.rb
module Api::V1
  class BeaconController < ApplicationController

    skip_before_action :verify_authenticity_token

    # GET /api/v1/beacon/get
    # take beacon id
    # return menu json
    def get
      beacon = Beacon.find_by_b_id(params[:id])
      if beacon
        @menu = Menu.find(beacon.menu_id)
        render template: 'api/v1/beacon/get', :layout => false
      else
        head 403
      end
    end

    private
  end
end

app/controllers/beacons_controller.rb
class BeaconsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_store
  before_action :set_beacon, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def show
    respond_with(@beacon)
  end

  def new
    @beacon = @store.beacons.new
    respond_with(@beacon)
  end

  def edit
  end

  def create
    @beacon = @store.beacons.new(beacon_params)
    if @beacon.save
      flash[:notice] = 'Menu was successfully created.'
    end

    respond_with(@store)
  end

  def update
    if @beacon.update(beacon_params)
      flash[:notice] = 'Menu was successfully updated.'
    end
    respond_with(@store)
  end

  def destroy
    @beacon.destroy
    respond_with(@store)
  end

  private
  def set_store
    @store = Store.find(params[:store_id])
  end

  def set_beacon
    @beacon = Beacon.find(params[:id])
  end

  def beacon_params
    params.require(:beacon).permit(:b_id, :menu_id)
  end
end

app/views/beacons/_form.html.erb
<%= simple_form_for @beacon, :url => @beacon.new_record? ? store_beacons_path : store_beacon_path(@store, @beacon),
                    :method => @beacon.new_record? ? :post : :patch, :html => {:data => {:validate => 'parsley'}} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :b_id, :label => 'Beacon ID', :input_html => {class: 'form-control',
                                                              :required => true,
                                                              "data-parsley-pattern" => '/^\d+-\d+$/',
                                                              "data-parsley-pattern-message" => 'Invalid beacon ID. You must enter a number hyphen number like "123-456"'} %>
    <label for="beacon_menu_id">Menu</label>
    <%= f.select :menu_id, options_from_collection_for_select(@store.menus, :id, :name, selected: @beacon[:menu_id]), {}, class: 'form-control' %>
    <br>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to 'Back', store_path(@store), :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/beacons/edit.html.erb
<div class="container">
  <h1>Editing beacon <%= @beacon.b_id%></h1>

  <%= render 'form' %>

</div>

app/views/beacons/new.html.erb
<div class="container">
  <h1>New beacon for <%= @store.name %></h1>

  <%= render 'form' %>

</div>