config/routes.rb
Rails.application.routes.draw do
  resources :stores do
    resources :menus
    resources :beacons
    resources :loyalty_programs
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users

  get 'api/v1/beacon/get' => 'api/v1/beacon#get'
  post 'api/v1/payment/pay' => 'api/v1/payment#pay'
end

app/models/store.rb
class Store < ActiveRecord::Base
  belongs_to :user
  has_many :menus
  has_many :beacons
  has_many :transaction_histories
  has_many :loyalty_programs
  validates_presence_of :name
  validates_presence_of :address
  validates_uniqueness_of :name
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  after_action :verify_authorized

  respond_to :html

  def index
    authorize User
    @stores = current_user.stores
    respond_with(@stores)
  end

  def show
    authorize @store
    respond_with(@store)
  end

  def new
    @store = current_user.stores.new
    authorize @store
    respond_with(@store)
  end

  def edit
    authorize @store
  end

  def create
    @store = current_user.stores.new(store_params)
    authorize @store
    flash[:notice] = 'Store was successfully created.' if @store.save
    respond_with(@store)
  end

  def update
    authorize @store
    flash[:notice] = 'Store was successfully updated.' if @store.update(store_params)
    respond_with(@store)
  end

  def destroy
    authorize @store
    @store.destroy
    respond_with(@store)
  end

  private
    def set_store
      @store = Store.find(params[:id])
    end

    def store_params
      params.require(:store).permit(:name, :address, :user_id)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_beacons.html.erb
<h2>
  Beacons
  <%= link_to new_store_beacon_path(@store), :class => 'btn btn-default' do %>
    <%= fa_icon 'plus'%> Add New Beacon
  <% end %>
</h2>

<% if @store.beacons.count == 0 %>
  <div class="text-center">
    <%= link_to new_store_beacon_path(@store), :class => 'btn btn-default btn-lg' do %>
      <%= fa_icon 'plus'%> Add New Beacon
    <% end %>
    <br>
    <small>This store does not have any beacons. Click the "Add New Beacon" to create one.</small>
  </div>
<% else %>


<table class="table">
  <thead>
  <th>Beacon ID</th>
  <th>Menu</th>
  <th></th>
  </thead>
  <tbody>
  <% @store.beacons.each do |beacon| %>
    <tr>
      <td><%= beacon.b_id %></td>
      <td><%= Menu.find(beacon.menu_id).name %></td>
      <td>
        <%= link_to edit_store_beacon_path(@store, beacon), :class => 'btn btn-primary btn-xs' do %>
          <%= fa_icon 'pencil' %> Edit
        <% end %>
        <%= link_to store_beacon_path(@store, beacon), method: :delete, data: { confirm: 'Are you sure?' },
                    :class => 'btn btn-danger btn-xs' do %>
          <%= fa_icon 'trash' %> Delete
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

app/views/stores/_form.html.erb
<%= simple_form_for @store, :html => {:data => {:validate => 'parsley'}} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to 'Back', :back, :class => 'btn btn-danger' %>
  </div>
<% end %>

app/views/stores/_loyalty_programs.html.erb
<h2>
  Loyalty Programs
  <%= link_to new_store_loyalty_program_path(@store), :class => 'btn btn-default' do %>
    <%= fa_icon 'plus'%> Add New Loyalty Program
  <% end %>
</h2>

<table class="table">
  <thead>
    <th>Start Date</th>
    <th>End Date</th>
    <th>Type</th>
    <th>Item/Menu</th>
    <th>Required Purchases</th>
    <th>Discount (%)</th>
    <th></th>
  </thead>
  <tbody>
  <% @store.loyalty_programs.each do |lp| %>
    <tr>
      <td><%= lp.start_date %></td>
      <td><%= lp.end_date %></td>
      <td><%= lp.s_type %></td>
      <td>
        <%= lp.item? ? Item.find(lp.s_id).name : Menu.find(lp.s_id).name %>
      </td>
      <td><%= lp.s_required %></td>
      <td><%= lp.s_discount %></td>
      <td>
        <%= link_to edit_store_loyalty_program_path(@store, lp), :class => 'btn btn-primary btn-xs' do %>
          <%= fa_icon 'pencil' %> Edit
        <% end %>
        <%= link_to store_loyalty_program_path(@store, lp), method: :delete, data: { confirm: 'Are you sure?' },
                    :class => 'btn btn-danger btn-xs' do %>
          <%= fa_icon 'trash' %> Delete
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>

</table>

app/views/stores/_menus.html.erb
<h2>
  Menus
  <%= link_to new_store_menu_path(@store), :class => 'btn btn-default' do %>
    <%= fa_icon 'plus'%> Add New Menu
  <% end %>
</h2>

<% if @store.menus.count == 0 %>
  <div class="text-center">
    <%= link_to new_store_menu_path(@store), :class => 'btn btn-default btn-lg' do %>
      <%= fa_icon 'plus'%> Add New Menu
    <% end %>
    <br>
    <small>This store does not have any menus. Click the "Add New Menu" to create one.</small>
  </div>
<% else %>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <% @store.menus.each_with_index do |menu, index| %>
    <div class="panel panel-default">
      <div class="panel-heading" role="tab" id="heading-<%=index%>">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapse-<%=index%>"
           aria-expanded="false" aria-controls="collapse-<%=index%>">
          <h4 class="panel-title">
            <%= menu.name %>
            <small>(<%= menu.items.count %> items)</small>
          </h4>
        </a>
      </div>
      <div id="collapse-<%=index%>" class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading-<%=index%>">
        <div class="panel-body">
          <div class="menu-buttons">
            <h4> <%= menu.name %>
              <%= link_to edit_store_menu_path(@store, menu), :class => 'btn btn-primary btn-xs' do %>
                <%= fa_icon 'pencil' %> Edit Menu
              <% end %>
              <%= link_to store_menu_path(@store, menu), :method => :delete,
                          :data => { confirm: 'Are you sure?' }, :class => 'btn btn-danger btn-xs' do %>
                <%= fa_icon 'trash' %> Delete Menu
              <% end %>
            </h4>
          </div>
          <div class="description">
            <%= menu.description %>
          </div>
          <h3>Items</h3>
          <table class="table">
            <thead>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            </thead>
            <tbody>
            <% menu.items.each do |item| %>
              <tr>
                <td><%= item.name %></td>
                <td><%= item.price %></td>
                <td><%= item.description %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  <% end %>
</div>
<% end %>

app/views/stores/_transaction_history.html.erb
<h2>Transaction History</h2>

<table class="table">
  <thead>
    <th>Time</th>
    <th>User</th>
    <th>Item</th>
    <th>Amount</th>
  </thead>
  <tbody>
    <% @store.transaction_histories.each do |th|%>
    <tr>
      <td><%= th.payment_time.localtime.strftime('%A, %d %b %Y %l:%M %p') %></td>
      <td><%= th.payer_id %></td>
      <td><%= Item.find(th.item_id).name %></td>
      <td><%= '$%.2f' % (th.amount/1000) %></td>
    </tr>
    <% end %>
  </tbody>

</table>

app/views/stores/edit.html.erb
<div class="container">
  <h1>Editing store</h1>

  <%= render 'form' %>

</div>

app/views/stores/index.html.erb
<div class="container">
<h1>
  My Stores
  <%= link_to new_store_path, :class => 'btn btn-default' do %>
    <%= fa_icon 'plus'%> New Store
  <% end %>
</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @stores.each do |store| %>
      <tr>
        <td><%= link_to store.name, store %></td>
        <td><%= store.address %></td>
        <td>
          <%= link_to edit_store_path(store), :class => 'btn btn-primary btn-xs' do %>
            <%= fa_icon 'pencil' %> Edit
          <% end %>
          <%= link_to store, method: :delete, data: { confirm: 'Are you sure?' },
                            :class => 'btn btn-danger btn-xs' do %>
            <%= fa_icon 'trash' %> Delete
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/stores/new.html.erb
<div class="container">
  <h1>New store</h1>

  <%= render 'form' %>

</div>

app/views/stores/show.html.erb
<div class="container">
  <h1>
    <%= @store.name %>
    <%= link_to edit_store_path(@store), :class => 'btn btn-primary' do %>
      <%= fa_icon 'pencil' %> Edit Store Details
    <% end %>
  </h1>
  <p>
    <strong>Name:</strong>
    <%= @store.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= @store.address %>
  </p>

  <p>
    <strong>Owner:</strong>
    <%= @store.user.email %>
  </p>

  <div role="tabpanel">

    <!-- Nav tabs -->
    <ul class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#menus" aria-controls="menus" role="tab" data-toggle="tab">Menus</a></li>
      <li role="presentation"><a href="#beacons" aria-controls="beacons" role="tab" data-toggle="tab">Beacons</a></li>
      <li role="presentation"><a href="#transaction-history" aria-controls="transaction-history" role="tab" data-toggle="tab">Transaction History</a></li>
      <li role="presentation"><a href="#loyalty_program" aria-controls="loyalty_program" role="tab" data-toggle="tab">Loyalty Programs</a></li>
    </ul>

    <!-- Tab panes -->
    <div class="tab-content">
      <div role="tabpanel" class="tab-pane active" id="menus">
        <%= render 'menus'%>
      </div>
      <div role="tabpanel" class="tab-pane" id="beacons">
        <% if @store.menus.count == 0 %>
          <h2>Beacons</h2>
          <small>You have to a menu before you can add a beacon.</small>
        <% else %>
          <%= render 'beacons'%>
        <% end %>
      </div>
      <div role="tabpanel" class="tab-pane" id="transaction-history">
        <%= render 'transaction_history'%>
      </div>
      <div role="tabpanel" class="tab-pane" id="loyalty_program">
        <%= render 'loyalty_programs'%>
      </div>
    </div>

  </div>


  <br><br><br> <!--TODO: this is bad, you should not do this Khanh....-->
  <%= link_to stores_path, :class => 'btn btn-default' do %>
    Back
  <% end %>

</div>