config/routes.rb
Rails.application.routes.draw do
  resources :stores do
    resources :menus
    resources :beacons
    resources :loyalty_programs
  end

  root to: 'visitors#index'
  devise_for :users
  resources :users

  get 'api/v1/beacon/get' => 'api/v1/beacon#get'
  post 'api/v1/payment/pay' => 'api/v1/payment#pay'
end

app/models/loyalty_program.rb
class LoyaltyProgram < ActiveRecord::Base
  enum s_type: [:item, :menu]
  belongs_to :store
  validates_presence_of :start_date
  validates_presence_of :end_date
  validates_presence_of :s_required
  validates_presence_of :s_discount

  def item_or_menu_name
    if item?
      return Item.find(s_id).name
    else
      return Menu.find(s_id).name
    end
  end

end

app/controllers/loyalty_programs_controller.rb
class LoyaltyProgramsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_store
  before_action :set_loyalty_program, only: [:show, :edit, :update, :destroy]

  respond_to :html, :json

  def show
    respond_with(@loyalty_program)
  end

  def new
    @loyalty_program = @store.loyalty_programs.new
    @loyalty_program.s_type = 0
    respond_with(@loyalty_program)
  end

  def edit
  end

  def create
    @loyalty_program = @store.loyalty_programs.new(loyalty_program_params)
    if @loyalty_program.save
      flash[:notice] = 'Menu was successfully created.'
    end

    respond_with(@store)
  end

  def update
    if @loyalty_program.update(loyalty_program_params)
      flash[:notice] = 'Menu was successfully updated.'
    end
    respond_with(@store)
  end

  def destroy
    @loyalty_program.destroy
    respond_with(@store)
  end

  private
  def set_store
    @store = Store.find(params[:store_id])
  end

  def set_loyalty_program
    @loyalty_program = LoyaltyProgram.find(params[:id])
  end

  def loyalty_program_params
    loyalty_program_params = params.require(:loyalty_program).permit(:s_type, :s_id, :s_required, :s_discount, :start_date, :end_date)
    loyalty_program_params[:s_type] = loyalty_program_params[:s_type].to_i
    return loyalty_program_params
  end
end

app/views/loyalty_programs/_form.html.erb
<%= simple_form_for @loyalty_program, :url => @loyalty_program.new_record? ? store_loyalty_programs_path : store_loyalty_program_path(@store, @loyalty_program),
                    :method => @loyalty_program.new_record? ? :post : :patch, :html => {:data => {:validate => 'parsley'}} do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.label :start_date %>
    <div class="input-group datepicker">
      <span class="input-group-addon datepickerbutton">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
      <%= f.text_field :start_date, :class => 'form-control', "data-format" => 'dd/MM/yyyy', :required => true, :value => (@loyalty_program.start_date.strftime('%d/%m/%Y') unless @loyalty_program.start_date.nil?) %>
      </span>
    </div>

    <%= f.label :end_date %>
    <div class="input-group datepicker">
      <span class="input-group-addon datepickerbutton">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
      <%= f.text_field :end_date, :class => 'form-control', "data-format" => 'dd/MM/yyyy', :required => true, :value => (@loyalty_program.end_date.strftime('%d/%m/%Y') unless @loyalty_program.end_date.nil?) %>
      </span>
    </div>

    <label for="loyalty_program_s_type">On an item or menu?</label>
    <%= f.select :s_type, options_from_collection_for_select([[0, 'Item'], [1, 'Menu']], :first, :last, selected: @loyalty_program[:s_type]), {}, class: 'form-control' %>
    <br>
    <div id="s_id_item" <%= 'hidden' unless @loyalty_program.item? %>>
      <label for="loyalty_program_s_id">Item</label>
      <%= f.select :s_id, options_from_collection_for_select(Item.where(menu_id: @store.menus.pluck(:id)), :id, :name, selected: @loyalty_program.item? ? @loyalty_program[:s_id] : nil), {}, class: 'form-control' %>
    </div>
    <div id="s_id_menu" <%= 'hidden' unless @loyalty_program.menu? %>>
      <label for="loyalty_program_s_id">Menu</label>
      <%= f.select :s_id, options_from_collection_for_select(@store.menus, :id, :name, selected: @loyalty_program.menu? ? @loyalty_program[:s_id] : nil), {}, class: 'form-control' %>
    </div>
    <br>
    <%= f.input :s_required, :label => 'Required amount' %>
    <%= f.input :s_discount, :label => 'Discount (%)' %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= link_to 'Back', store_path(@store), :class => 'btn btn-danger' %>
  </div>
<% end %>

<script>
  $('.datepicker').datetimepicker({
    format: 'DD/MM/YYYY'
  });

  $('#s_id_menu select').removeAttr('name');
  $('#loyalty_program_s_type').on('change', function(e) {
    if($(this).val() == '0') {
      $('#s_id_menu').hide();
      $('#s_id_menu select').removeAttr('name');
      $('#s_id_item').show();
      $('#s_id_item select').attr('name', 'loyalty_program[s_id]');
    } else {
      $('#s_id_item').hide();
      $('#s_id_item select').removeAttr('name');
      $('#s_id_menu').show();
      $('#s_id_menu select').attr('name', 'loyalty_program[s_id]');
    }
  });
</script>

app/views/loyalty_programs/edit.html.erb
<div class="container">
  <h1>Editing Loyalty Program <%= @loyalty_program.id %> of <%= @store.name %></h1>
  <%= render 'form' %>
</div>

app/views/loyalty_programs/new.html.erb
<div class="container">
  <h1>Creating New Loyalty Program for <%= @store.name %></h1>
  <%= render 'form' %>
</div>